services:
  node:
    image: 'node:20'
    container_name: six-cities-node
    user: 'node'
    working_dir: /home/node/app
    stdin_open: true
    tty: true
    volumes:
      - ./:/home/node/app
    ports:
      - 127.0.0.1:3123:3123
